### ISSUE TITLE
Getting readouts in demo #3 even if my ant+ usb dongle is not plugged in

### ISSUE THREAD

**Issue by tjthejuggler** [half2me/libant#14]
I am probably misunderstanding something, but even when I have no ant+ dongle plugged in, I am still getting a readout that looks like this:

...
19052 Cadence: 76.90rpm (avg: 84.48rpm)
19052 Total Distance: 333.26m
19052 Total Revolutions: 41
19052 Power: 251W
19052 Speed: 11.24m/s (avg: 11.71m/s)
19052 Cadence: 73.14rpm (avg: 85.81rpm)
19052 Total Distance: 343.74m
19052 Total Revolutions: 42
19052 Power: 252W
19052 Speed: 11.24m/s (avg: 11.61m/s)
19052 Cadence: 73.14rpm (avg: 85.10rpm)
19052 Total Distance: 343.74m
19052 Total Revolutions: 42
19052 Power: 245W
19052 Speed: 11.24m/s (avg: 11.51m/s)
19052 Cadence: 73.14rpm (avg: 84.39rp
...

is this expected behavior?

**Comment by tjthejuggler** [comment]
I should also mention that this is without my garmin watch or any other device running

**Comment by half2me** [comment]
Hi @tjthejuggler if by demo 3 you mean the "pcap demo" this doesn't use the ANT+ device, but rather reads data from a packet capture "pcap" file. This is meant for replaying recorded ant+ data. Also please note that this library is no longer maintained. I have a newer library available for golang, but I don't have the time to maintain these anymore unfortunately.

**Comment by tjthejuggler** [comment]
Thanks for the response. That makes sense then about the packets. I'll check out the other project. All I am trying to do is stream Garmin watch accelerometer data to my Linux pc with an ant+ USB dongle. Should your go project be able to do this?

**Comment by half2me** [comment]
it should absolutely be able to handle that. Please note the examples all use `RxScan` which essentially listens to all ANT+ traffic without filtering to any particular device. You do get the id and type though, so you can easily just filter out the data for yourself if you know the ant+ id of your device.

**Comment by tjthejuggler** [comment]
Excellent, thanks so much, I really appreciate you taking the time to help me with this!

**Comment by half2me** [comment]
@tjthejuggler no worries. Have fun with your project!
